export const genres = [
  { genreId: 2, name: 'Point & click' },
  { genreId: 4, name: 'Fighting' },
  { genreId: 5, name: 'Shooter' },
  { genreId: 7, name: 'Music' },
  { genreId: 8, name: 'Platform' },
  { genreId: 9, name: 'Puzzle' },
  { genreId: 10, name: 'Racing' },
  { genreId: 11, name: 'RTS' },
  { genreId: 12, name: 'RPG' },
  { genreId: 13, name: 'Simulator' },
  { genreId: 14, name: 'Sport' },
  { genreId: 15, name: 'Strategy' },
  { genreId: 16, name: 'TBS' },
  { genreId: 24, name: 'Tactical' },
  { genreId: 26, name: 'Quiz/Trivia' },
  { genreId: 25, name: "Hack'n'slash" },
  { genreId: 30, name: 'Pinball' },
  { genreId: 31, name: 'Adventure' },
  { genreId: 33, name: 'Arcade' },
  { genreId: 34, name: 'Visual Novel' },
  { genreId: 32, name: 'Indie' },
  { genreId: 35, name: 'Board Game' },
  { genreId: 36, name: 'MOBA' },
];

export const alphabet = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
];

export const igdbSortMethods = [
  'total_rating',
  'first_release_date',
  'rating',
  'aggregated_rating',
];

export const igdbSortOrders = ['asc', 'desc'];
